default:
  # File routes
  'POST /file': 'FileController#upload_file'
  'GET /file/:id': 'FileController#get_file'
  'DELETE /file/:id': 'FileController#delete_file'
  'GET /file/show/:id': 'FileController#show_file'
  'GET /file/download/:id': 'FileController#download_file'

  # Image routes
  'GET /image/:width/:height/:id.:format': 'ImageController#show_image'

  'GET /image/width/:width/:id.:format': 'ImageController#show_image'
  'GET /image/height/:height/:id.:format': 'ImageController#show_image'
  'GET /image/scale/:scale/:id.:format': 'ImageController#show_image'
  
  'GET /image/:width/:height/:crop_origin_x/:crop_origin_y/:id.:format': 'ImageController#show_image'
  'GET /image/:scale/:width/:height/:crop_origin_x/:crop_origin_y/:id.:format': 'ImageController#show_image'

  # Misc. routes
  'GET /health-check': 'DefaultController#health_check'
